language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy

before_script:
  - gem -v
  - ruby -v
  - travis_retry gem install nats --pre
  - which nats-server
  - nats-server -d

install:
  - travis_retry pip install --upgrade .

script: py.test

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
    - python: pypy
